### PR TITLE
PD1-1940 add sentry log

### PR DESCRIPTION
**Pull request by kundojo**

### CODE REVIEW

**Comment by ghost** [comment]
Isn't it kinda wrong to add credentials to public fork? Even for logs.

**Comment by ghost** [comment]
I would rather add the option to read them from non-git config file

**Comment by m-vadzay** [comment]
This is actually a good idea too. 
But our Sentry DSNs are not as critical as passwords or smth like that.

**Comment by ghost** [comment]
Still kinda private info

**Comment by kundojo** [comment]
So, is it okay if i will take it from `.env` file?

**Comment by ghost** [comment]
I would say yes. It's a good place to store that type of values.

**Review by ghost — APPROVED** [review]

**Comment by kundojo** [comment]
@m-vadzay please, tell me if it is okay for you to create local `.env` files and then I will merge it
```
SENTRY_DSN = "https://some.sentry.midndoji.com/xx"
```

**Pull request merged**
